name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  test-ubuntu:
    name: "test on ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        run: pipx install uv
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Hoplite and its dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsndfile1 ffmpeg
          uv pip sync --system requirements.txt
          uv pip install --system -e . --no-deps
      - name: Test taxonomy with unittest
        run: python -m unittest discover -s perch_hoplite/taxonomy -p "*test.py"
      - name: Test zoo with unittest
        run: python -m unittest discover -s perch_hoplite/zoo -p "*test.py"
      - name: Test zoo tensorflow models with unittest
        run: python -m unittest discover -s perch_hoplite/zoo/tests_tf -p "*test.py"
      - name: Test agile with unittest
        run: python -m unittest discover -s perch_hoplite/agile/tests -p "*test.py"
